data_config:
  target: "Exited"
  features:
    numeric:
      - CreditScore
      # ... (resto de features)
    categorical:
      - Geography
      # ... (resto de features)

preprocessing:
  imputer_strategy_numeric: "median"
  imputer_strategy_categorical: "most_frequent"

models:
  logreg:
    name: "LogisticRegression"
    params:
      C: 1.0
      solver: "liblinear"

  rf:
    name: "RandomForestClassifier"
    params:
      n_estimators: 100
      max_depth: 10
      min_samples_leaf: 4

  gbc:
    name: "GradientBoostingClassifier"
    params:
      n_estimators: 150
      learning_rate: 0.1
      max_depth: 5